### ISSUE TITLE
Integration with the GPL

### ISSUE THREAD

**Issue by Lashette** [ContributorCovenant/hippocratic-license#31]
I'm a fan of using the GPL for software projects due to its strong copy left nature. When I saw this I thought it was a rather good idea, but I also wish to have the strong copy left nature of the GPL. I'd like to see if we can have a constructive discussion on integrating the hippocratic license with the GPL!

**Comment by dannycolin** [comment]
Someone in #6 pointed out that the Hippocratic License "is not GPL-compatible, because it restricts FSF's freedom 0, the freedom to use the software for any purpose". 

I'm not a lawyer so I don't know if it really goes against freedom 0 or not. But, I think it'll be the first thing to find out. Maybe, someone at the [Software Freedom Conservancy](https://sfconservancy.org) could help us.

**Comment by yawpitch** [comment]
Though Freedom 0 isn't actually part of the text of the GPL, the GPL's free software provisions certainly were intended to extend the spirit of the FSF's meaning of ["Free Software"](https://www.gnu.org/philosophy/free-sw.en.html) to anything licensed under the GPL, thus software licensed under the GPL really _should_ convey with it the copyright assignment necessary to use the software for _any_ inethical, illegal, and/or immoral purpose.

So no, they're not really compatible, or able to be integrated. 

But, that said, the copyleft provisions and language of the GPL are somewhat distinct from the free software provisions it also incorporates. It would be nice to see a copyleft version of the Hippocratic License that took a swing at incorporating those _without_ the "free as in free from moral consequence" parts of the original.

**Comment by Aspie96** [comment]
> Though Freedom 0 isn't actually part of the text of the GPL

Quoting GPL 3:
> This License explicitly affirms your *unlimited* permission to run the unmodified Program.

According to the GPL, all rights provided trough the license are irrevokable. This very much includes the mentioned one.

I obviously agree with the incompatibility.

Note: I think you might have meant that the verbatim text of Freedom 0 is not part of the GPL, rather than the fact that Freedom 0 is not implied by the GPL. In which case, I misunderstood.

**Comment by yawpitch** [comment]
I meant solely that Freedom 0 was neither mentioned in the GPL, nor was its text incorporated verbatim into it ... it is not a concept that can be identified by that name within the text of the license itself. One can therefore certainly refer to Freedom 0 when discussing the intellectual basis of the GPL, but one cannot really state that "X is not GPL compatible _because_ it restricts [any given other utterance of the creators of the GPL]" ... the explicit reason for incompatibility must be found in the text itself.

I agree that within the text itself there is such an incompatibility, but "unlimited permission to run the unmodified program" is not identical in either meaning or wording to "[t]he freedom to run the program as you wish, for any purpose".

**Comment by yawpitch** [comment]
@Lashette, given the above, you might consider closing this issue and starting one asking for a strong copyleft version of the Hippocratic License. If the ethical considerations of the HL make it incompatible with the OSD then it's _definitely_ incompatible with the GPL, since the FSF is if anything more libertarian than the OSI.

**Comment by Aspie96** [comment]
Thank you for clarifying!

> is not identical in either meaning or wording
Of course the wording is very different.
Still, I would argue works under GPL do indeed provide freedom 0. That is
because running the program is in no way restricted by the license (it even
allows you to run modified versions of the program, as well, even combining
it with incompatible software).

> X is not GPL compatible *because* it restricts [any given other utterance
of the creators of the GPL]
Oh, I agree with that.
It's just hard to imagine, for me at least, how a non-free license could
possibly be compatible with the GPL (not just this license), since
derivative works must be under GPL (or AGPL, as well), which doesn't allow
any additional restriction than those explicitly stated in the license.

Il giorno dom 22 dic 2019 alle ore 14:03 Michael Morehouse <
notifications@github.com> ha scritto:

**Comment by Aspie96** [comment]
I agree with Michael.

Il giorno dom 22 dic 2019 alle ore 14:12 Michael Morehouse <
notifications@github.com> ha scritto:

**Comment by yawpitch** [comment]
> Of course the wording is very different. Still, I would argue works under GPL do indeed provide freedom 0. That is because running the program is in no way restricted by the license (it even allows you to run modified versions of the program, as well, even combining it with incompatible software).

See I try to be very careful with my distinctions here. Freedom 0 is a statement of principles, but those principles extend _well_ outside what a copyright assignment can do. The GPL, as a license, can _only_ do what a copyright assignment can do.

So the GPL extends permission to run the program, and it says that permission is unrestricted. That's fine, to the extent that the author can extend that permission.

Freedom 0, though, says you have "the freedom to run the program as you wish, for any purpose" ... but that is _not_ within the purview of copyright assignment, and goes beyond what the GPL _can_ extend. The author of a work cannot extend to the assignee the freedom to use that work for illegal purposes, for instance ... the copyright assignee didn't enjoy that right before the assignment, they sure as heck don't enjoy it after, merely as a consequence of downloading a piece of software licensed under the GPL.

Conversely, though, it is _entirely_ within the rights (and I'd argue responsibility) of the author to _not_ extend permission to uses they consider immoral. The holder of copyright has an absolute moral right to be _more_ restrictive than the letter of the law, and can be, right up until those restrictions themselves become illegally discriminatory, such as when motivated by racial animus. They can be judged by the market, and maybe history, for those restrictions, but the purpose of copyright assignment is to protect their interest in how the work of their own mind gets disseminated ... it's _not_ to protect the interest of others in being free to do whatever they want, whenever they want.

**Comment by Aspie96** [comment]
>  but those principles extend *well* outside what a copyright assignment
can do.
Ah, ok.
Agree with you here 100%.

For instance, there is a lot of software with free licenses (such as Apache
license) which isn't actually free software.
I'd argue mere legal restrictions don't make software non-free, as the
restriction doesn't have anything to do with the software itself (for
instance, if I buy a knife, I obviously cannot use it to kill anybody, but
nor could I kill anybody without using a knife: the restrcition doesn't
come from buying the knife in any way and no knife can allow for that).

Thanks for clarifying.

Il giorno dom 22 dic 2019 alle ore 15:27 Michael Morehouse <
notifications@github.com> ha scritto:

**Comment by yawpitch** [comment]
Ok, good ... but then by extension you can't really see the HL as non-free.

The UDHR is a foundational document of international law; any act that is found to have manifestly violated the UDHR is, de facto, a violation of at least the spirit of international law, even if it is not, de jure, illegal under your local law ... thus the HL is really just an explicit statement that the author does not assign to the user freedoms to act in ways they're not already _truly_ free to act in.

Where local law falls short of the UDHR I would say that there's a _far_ more significant concern for fundamental freedoms than can be addressed by a software license, but I would argue, strongly, that restricting users to the closest thing we've got to a universally agreed baseline for moral action doesn't _inherently_ make the user any less free than they already were, in precisely the same manner as that knife ... they never _truly_ enjoyed the freedom to stab someone with it, absent repercussion, and _if_ the manufacturer decided to put a label on there saying, expressly, that nothing in its sale of its product to you grants you the freedom to stick it in someone else I doubt there would be any significant controversy from the Open Cutlery community.

**Comment by Aspie96** [comment]
Local laws absolutely do fall short of the UDHR, thus this is an additional
restriction.
Assuming the license is useful, it is non-free (since its main restrictions
are on use). If it is free, then it is not useful.

> in precisely the same manner as that knife
But it would in a country in which killing with a knife was legal.

> nothing in its sale of its product to you grants you the freedom to stick
it in someone else
It would still be a restriction, as laws are contingent.

See it this way: free licenses, by defintion, allow usage for any purpose.
That doesn't mean you can use something for any purpose, because being
allowed by the software author isn't enough.
Regardless, if you do use it for illegal purposes (and violating human
rights isn't always illegal, although always immoral), you will never be
violating copyright law by doing so.

Let's pretend that violating human rights is indeed illegal. Even in that
case, we know have two places the restriction comes from: state law and the
licenses. The penalty in violating one or the other is clearly different,
but they will be equally responsable for the limitation.

In my knife example, I was pointing out how the seller of the knife
wouldn't be responsable for the limitation; if the limitation is expressely
stated, that's a very different case.

Licenses cannot replace the laws. I don't think freedom 0 has ever been
interpreted as literally creating a new legal system in which there are no
restrictions on running the program.

Il giorno dom 22 dic 2019 alle ore 16:44 Michael Morehouse <
notifications@github.com> ha scritto:

**Comment by yawpitch** [comment]
Violating human rights _is_ illegal ... if your local government thinks otherwise then your local government is illegitimate. The only questions are when and to what degree will they reap what they've sewn. The "when" is, always, "eventually".

And thinking about licenses replacing laws, or that copyright licensure is the wrong forum, are both common, but ill-conceived, red herrings; no, licenses don't establish the absolute boundaries of your freedom, that's the job of the law. The job of the license is solely to say under what circumstances you're allowed to replicate the copyrighted work of another, in other words the relative or soft boundaries of our freedom. And that's precisely why licenses are necessary, because they're where authorial responsibility comes in to play. The law has established that the copyright is solely the author's right to assign; they can only do so by an act of volition, in the form of a license. Within the boundaries established by the law the license, then, is _precisely_ the point at which the author can condone your actions by granting, or denounce your actions by withholding, that assignment.

Since copyright is an internationally-recognized human right that has strong legal protections in most states -- indeed often much stronger legal protections than most other human rights -- it's the perfect forum in which to establish a moral and ethical floor. If you are willing to violate the UHDR then you're _probably_ willing to violate my copyright -- at which point you'll have _necessarily_ broken _both_ human rights and copyright laws -- but if you're _not_ willing to violate my copyright and I fail to state that you can't use it to violate the _other_ human rights upon which I depend then I, personally, bear moral responsibility for your acts.

Thus a "free" license that does not state such a floor is an abdication of personal responsibility by the author, and a "non-free" license that does state such a floor is still free, because you remain free to do anything you _should_ be doing.

**Comment by yawpitch** [comment]
Regardless, at this point we need to end this line of discussion; it's gone way off the manifest purpose of this issue. We agree that integration with the GPL is effectively impossible, but that (likely optional) copyleft provisions for the HL aren't.

**Comment by Aspie96** [comment]
Yes, we absolutely agree with the conclusion, even if we disagree with the
arguments being made.

Il giorno dom 22 dic 2019 alle ore 17:45 Michael Morehouse <
notifications@github.com> ha scritto:

**Comment by decentral1se** [comment]
> due to its strong copy left nature.

I think you might find interest in https://github.com/EthicalSource/hippocratic-license/issues/21, https://github.com/EthicalSource/hippocratic-license/issues/6 and https://github.com/EthicalSource/hippocratic-license/issues/42 :+1: 

(Sorry to resurrect an old issue...)
