### ISSUE TITLE
Please remove ALL mention of open source

### ISSUE THREAD

**Issue by MrRawes** [ContributorCovenant/hippocratic-license#87]
Duplicate of #7 and #34
[in light of recent events](https://opensource.org/blog/court-affirms-its-false-advertising-to-claim-software-is-open-source-when-its-not)
also saying the definition of open source is more valid then a group dedicated to open source is ridiculous IMO

**Comment by rafaelcastrocouto** [comment]
really dude? 🙄

**Comment by Aspie96** [comment]
(I am not a lawyer and this is not legal advice).

While I agree that "Open Source" has a clear meaning and while I belive that what this project is trying to achieve is equivocation, that OSI article is quite misleading.

I usually disagree with Kyle Mitchell, but I believe he is (mostly) right in this case: https://writing.kemitchell.com/2022/03/17/OSI-Neo4j-PureThink.html

Government agencies definitely do use and understand "open source" correctly. The term (although translated) also appears in Italian law and it is interpreted correctly by government agencies.

I expect that a US or European court would, if it had to rule on the meaning of "open source", would do so correctly, but this isn't what happened here.

Personally, I believe this project has been unsuccessful enough that we can and should stop worrying about it.

The only two cases of somewhat well-known project adopting this did so with complete disregard for the previous license, showing a complete lack of understanding of (and/or care for) copyright law. Which is to be expected by someone using the Hippocratic License.

We should definitely uphold the standard interpretation of the OSD. I believe the best way, at this stage, would be a combination of the deductive and inductive (by listing well known examples of uncontroversially FLOSS licenses) approaches, in legislation as well as contracts. We should also advocate for a weaker reliance on OSI/FSF by government agencies, with the purpose of stabilizing how they will interpret the OSD in case OSI gets corrupted (i.e. making sure they rely on OSD-compliance rather than OSI-approval).

I believe this specific threat to open source isn't a significant danger, and that we should focus on other issues (whether they come from the ethical source movement or other hostile initiatives).

**Comment by MrRawes** [comment]
yes

------- Original Message -------

**Comment by erlend-sh** [comment]
The Hippocratic license has already been a major success by means of driving a very necessary dialog about ethics in the open source community. Even multi-decade proponents of traditional open source licensing like [Dries Buytaert of Drupal now agrees](https://pca.st/episode/36872d0a-532c-4616-a0cc-855dabafe643) that we need more innovation in licensing to prevent stagnation.

Instead of being a disruptive presence in well-meaning projects that very necessarily challenge the status quo, kindly educate yourselves about the open software movement as a whole and divert your energy into building on our shared Commons in an additive rather than subtractive manner.

https://writing.kemitchell.com/lists/Antidote.html
https://openeveryone.substack.com/p/open-source-for-everyone

**Comment by Aspie96** [comment]
The intellectually honest way to challange the status quo is to oppose open source licensing, and support a different licensing scheme instead.

This has happened several times in the past and I've got absolutely no issue with that whatsoever.

For ideas to be discussed, and for it to be possible to compare different licensing schemes, we need precision in our language.

Interestingly, @DEGoodmanWilson, in his [well known article](https://dev.to/degoodmanwilson/open-source-is-broken-g60), doesn't attempt to redefine terms, but rather openly expresses his views, in a clear way, and openly opposes the open source licensing model.

While I disagree with his article, and while I think he is plain wrong in many aspects, there is abslutely no issue with that, whatsoever. He still achieves the goal of challanging the status quo (even though it's not a very big challange), without needing for well-established terms to change their meaning.

I do not have any issue with the Hippocratic License at all. It's simply another proprietary license; it's also a license that I'd never use; I'd also never use software under that license. But there are many many licenses like that.
The only issue being discussed is the fact that it is claimed to be a license "for open source", while it clearly isn't.

Whether we need that kind of licensing is a completely independent and orthogonal issue and it shouldn't be discussed as if it was even remotely connected. If indeed there is any merit to this kind of licensing, it should be able to stand on its own, without having to ride the success of the open source licensing scheme.

There is a class of software licenses which is referred to as "open source licenses". It's also basically the same class as "free software licenses" (the exceptions lay on the very boundery of the category and rarely exist in practice).

What I want is for people to be able to advocate for any licensing scheme that they prefer. For that, there should be a clear shared term for each licensing scheme being discussed. I absolutely want there to be a term for licensing schemes that I disagree with to exist, because my opposition to an idea doesn't rely to the lack of words to express that idea.

It is my impression, however, that the intention of "some" is to change language in such a way that there is no term for a particular class of licenses (for which currently the term is "open source"), defined in a certain way, so that there is no clean way to clearly express support for that kind of licenses (and no other), without risk of equivocation.

The goal is to shift the meaning of existing words in a way that accomodates the "ethical source" licensing scheme. While that has been completely obvious from the very beginning, it has always been confirmed in https://github.com/EthicalSource/hippocratic-copyleft/issues/1#issuecomment-640829697.

**Comment by rafaelcastrocouto** [comment]
> even though it's not a very big challange

Yes it is, you don't see an awesome project like this everyday.

> It's simply another proprietary license

No it's not, and if you and everyone else here are able to understand that, then there's clearly no need for this vocabulary inquisition. As long as it's free and open access, then you can call it open source.

> it's also a license that I'd never use

Then whatahell are you doing here wasting our time, don't you have something better to do?

And for christ sake, as the initial commit msg points out: this have been discussed several times before. Find something useful to do with your life ... jesus!

**Comment by realpixelcode** [comment]
> It's simply another proprietary license

Oh my god, since when isn't it standard practice anymore to inform oneself about the topic one is talking about? Please, for god's sake, read the following excerpt from version 3.0:

> Grant of Copyright License: Subject to the terms and conditions of this License,
Licensor hereby grants to Licensee a worldwide, non-exclusive, no-charge,
royalty-free copyright license to use, copy, modify, prepare derivative work,
reproduce, or distribute the Software, Licensor authored modified software, or
other work derived from the Software.
>
> Grant of Patent License: Subject to the terms and conditions of this License,
Licensor hereby grants Licensee a worldwide, non-exclusive, no-charge, royalty-
free patent license to make, have made, use, offer to sell, sell, import, and
otherwise transfer Software.

**Comment by MrRawes** [comment]
> > It's simply another proprietary license
> 
> Oh my god, since when isn't it standard practice anymore to inform oneself about the topic one is talking about. Please, for god's sake, read the following excerpt from version 3.0:
> 
> > Grant of Copyright License: Subject to the terms and conditions of this License,
> > Licensor hereby grants to Licensee a worldwide, non-exclusive, no-charge,
> > royalty-free copyright license to use, copy, modify, prepare derivative work,
> > reproduce, or distribute the Software, Licensor authored modified software, or
> > other work derived from the Software.
> > Grant of Patent License: Subject to the terms and conditions of this License,
> > Licensor hereby grants Licensee a worldwide, non-exclusive, no-charge, royalty-
> > free patent license to make, have made, use, offer to sell, sell, import, and
> > otherwise transfer Software.

so, [it is not open source period.](https://nitter.net/OpenSourceOrg/status/1176229398929977344?ref_src=twsrc%5Etfw)
(we are talking about the OSD layed out by OSI anyway)

**Comment by MrRawes** [comment]
> > It's simply another proprietary license
> 
> Oh my god, since when isn't it standard practice anymore to inform oneself about the topic one is talking about? Please, for god's sake, read the following excerpt from version 3.0:
> 
> > Grant of Copyright License: Subject to the terms and conditions of this License,
> > Licensor hereby grants to Licensee a worldwide, non-exclusive, no-charge,
> > royalty-free copyright license to use, copy, modify, prepare derivative work,
> > reproduce, or distribute the Software, Licensor authored modified software, or
> > other work derived from the Software.
> > Grant of Patent License: Subject to the terms and conditions of this License,
> > Licensor hereby grants Licensee a worldwide, non-exclusive, no-charge, royalty-
> > free patent license to make, have made, use, offer to sell, sell, import, and
> > otherwise transfer Software.

can you explain why this means it is NOT a proprietary license, since thee are other terms which make it proprietary

**Comment by realpixelcode** [comment]
@MrRawes “Proprietary” is a synonym for “all rights reserved” which obviously is not the case here.

**Comment by Aspie96** [comment]
> “Proprietary” is a synonym for “all rights reserved”

No, it's not. A license is a permission or an authorization. Every license authorizes the licensee to exercise some of the rights of the licensor. That's what a license is, it's true for all kinds of licenses. A document which doesn't grant permissions would not be a license, neither proprietary nor open source, nor of any other kind.

"All rights reserved" doesn't actually mean much at all and I've seen it used in many contexts with widely different meanings (or, more commonly, no meaning at all). If by "all rights reserved" you mean that no right is licensed, then an "all rights reserved" license would be a logical contraddiction.

In practice, the phrase "all rights reserved" is used in some licenses simply to mean that the copyright holder continues to hold all rights. That's true regardless of the kind of license. It's true for open source licenses and proprietary licenses alike. Many permissive BSD-like licenses contain the phrase and it's unclear whether such phrase has any legal effect at all whatsoever (since what it states is already the legal default).

**Comment by realpixelcode** [comment]
>Every license authorizes the licensee to exercise some of the rights of the licensor.

No, certainly not. There are so many closed-source programs whose licences only permit usage under certain conditions but explicitly prohibit the re-destribution.

>an "all rights reserved" license would be a logical contradiction

I did not claim that “all-rights-reserved licences” existed.

>it's unclear whether such phrase has any legal effect at all whatsoever

At least in Germany, it is technically impossible to “give away” your copyright, the only thing you can do is granting “licence rights” to everyone.

**Comment by rafaelcastrocouto** [comment]
Sometimes I wonder why there are some people so annoyed by this project.
If you won't use, why come here and waste everyone time while achieving absolutely nothing?

The idea behind this project is VERY simple ... we want to keep our code open to the public while keeping clear that we are not ok with it being used for something that goes agains basic human rights. 

Everytime you guys pop up here to throw stones you just sound like:
> "it's not free and open access if I can't make a human organ traffic network with it"

If you want to remove something, fork the rep and delete it ... done. You can even make a PR but as you can see, no one will aprove it ... so you can just call your rep "not-open-hippocratic-license" or whatever you want and go on with your life

**Comment by MrRawes** [comment]
> Sometimes I wonder why there are some people so annoyed by this project. If you won't use, why come here and waste everyone time while achieving absolutely nothing?
> 
> The idea behind this project is VERY simple ... we want to keep our code open to the public while keeping clear that we are not ok with it being used for something that goes agains basic human rights.
> 
> Everytime you guys pop up here to throw stones you just sound like:
> 
> > "it's not free and open access if I can't make a human organ traffic network with it"
> 
> If you want to remove something, fork the rep and delete it ... done. You can even make a PR but as you can see, no one will aprove it ... so you can just call your rep "not-open-hippocratic-license" or whatever you want and go on with your life

here are some problems
1. i highly dout these orgonisations will care about this license
2.  the enforceability is unlikely
3. in for example debian, it would be in the "nonfree" repository

**Comment by Aspie96** [comment]
> "it's not free and open access if I can't make a human organ traffic network with it"

I've not seen any claim about "open access", only "open source".

This license doesn't even claim to be "for open access", so whether it is suited for open access or not is a completely irrelevant question. It doesn't have to be.

Likewise, there is absolutely no issue with publishing licenses that are not open source, and there would be no issue with this project if it didn't claim the license is for open source.

> If you want to remove something, fork the rep and delete it ... done.

Oh, yes. There is an open attempt to mislead the community about the nature of open source, as well as to change language so that it's less clear (such that there are no words to describe a specific set of licenses). But one can create a fork which doesn't do the same thing.

A foundamentally immoral project which is openly hostile both to the open source movement and to the language clarity required for intellectually honest discussion about licensing should expect people who care about either one of these things to bite back.

**Comment by rafaelcastrocouto** [comment]
@MrRawes no one here is discussinh whether it will be enforced, cared, etc. That ain't the subject that you propopsed for the issue here.

@Aspie96  the only immoral thing here is your false intelectual honesty.

**Comment by MrRawes** [comment]
> @MrRawes no one here is discussinh whether it will be enforced, cared, etc. That ain't the subject that you propopsed for the issue here.
> 
> @Aspie96 the only immoral thing here is your false intelectual honesty.

i apologise

**Comment by realpixelcode** [comment]
>1. i highly dout these orgonisations will care about this license
>2. the enforceability is unlikely

Just let that be the licensor's problem.

**Comment by realpixelcode** [comment]
@Aspie96 While I _know_ that there is a thing called "Open Source Definition", I highly disagree with it – not necessarily with its actual content but mainly with its title. You see, in real life I've never seen the term “open-source” being used to say that software is licensed under free conditions. That's also what I understand by the term “FOSS” (Free and Open-Source Software) – software that is not only open-source but can also be freely re-used. I've only ever heard it in contexts where the point was that the source code was accessible at all, not that it could freely be re-distributed. The fact that there is some definition is not to be confused with “language clarity” if said definition just isn't universally adopted.

Also, claiming a licence, that tries to enforce human rights, to be “immoral” is, well, irritating – mildly expressed. Are you really sure that it's the OES that is being hostile towards others?

**Comment by Aspie96** [comment]
> @Aspie96 the only immoral thing here is your false intelectual honesty.

Are you just going to state this as a claim, or are you going to show in what way I am intellectually dishonest?

> You see, in real life I've never seen the term “open-source” being used to say that software is licensed under free conditions.

This is one of the few responses that are given to the opposition to the term "open source" which is on point (I am not saying I agree, just that it doesn't address a completely different topic).

I've seen the term "open source" being used in the text of laws and policies by government agencies. I would defenitely call that "real life", since it has real consequences.

But I believe that by "real life" you refer to day to day informal interactions, rather than policies, laws and such, or even projects. In that case, it essentially comes down to anecdotal personal experience which, by its very nature, cannot really be verified or discussed (in most cases).

Luckly, sources exist to verify what the general consensus about the meaning of words is.
Usually dictionaries do a good job at this (that's what they are made for), but I've found high inconsistencies, and inaccuracies, when referring to technical topics: definitions that neither one of us would find accurate, or even remotely familiar (for instance, one Italian dictionary defines "open source" as "free of copyright", which I believe they thought was a good enough approximation for non-technical users).
A source which isn't always accurate but always thrives to agree with the general consensus, however, does exist: it's Wikipedia. While for matters of fact it's not always a reliable source, it is a great way to check for consensus in the usage of language: https://en.wikipedia.org/wiki/Open-source_software

In addition to all of this, as I said, Willson has used the term "open source" in what I'm arguing is the standard way and he is one of the prominent people in EOS. In fact, he is one fo the members of the GitHub organization.

> Also, claiming a licence, that tries to enforce human rights, to be “immoral” is, well, irritating

What I call immoral is the open attempt to change language to accomodate a new licensing scheme. A user has admitted that this was the intention in the "hippocratic-copyleft" repository, which I think can be safely considered to be part of this project.

I never said the text of the license itself has anything immoral about it. I was referring to the project behind it.

> Are you really sure that it's the OES that is being hostile towards others?

I didn't say it's hostile towards any individual. I said it's hostile to the open source movement and to clarity in language.

Note that they changed, multiple times, the meaning of their own terms. This is what "ethical source" used to mean:
https://web.archive.org/web/20200308160424/https://ethicalsource.dev/definition/

This is what it meant later:
https://web.archive.org/web/20201101062744/https://ethicalsource.dev/definition/

In essence, the very thing the movement was meant to be about changed drastically.

These are not the only two versions of the definition, by the way, but the contrast is striking enough to show that clarity in language had never been the intention, and that the movement itself, indeed, has never had any clear purpose or any level of consistency. The only way in which it has always been consistent is its willingness to associate itself with "open source".

The ethical source movement started off showing its distaste for the better regognized FLOSS organizations. It's a distaste I share, although for very different reasons. This isn't an issue, just something that I believe should be reminded from time to time. It's no longer on the website, but archives don't lie:
> And the organizations that claim ownership of the definitions of free and open source software have ignored our community’s call for ethical solutions to these problems. We’ve seen the Free Software Foundation continue to [support its incredibly problematic founder](https://web.archive.org/web/20200129143333/https://identi.ca/lxoliva/note/10dsqBaMTqKonl898d_U-w). We’ve seen the Open Source Initiative continuing to prioritize [software freedom over ethical concerns](https://web.archive.org/web/20200129143333/https://opensource.org/faq#evil).

> The time has come to reclaim authority over what it means to develop software in the open, without compromising ourselves or the [universal values of human rights](https://web.archive.org/web/20200129143333/https://www.un.org/en/universal-declaration-human-rights/).

Then, as you know, both Coraline and Tobie run for the board of OSI. And lost. Then, Coraline published misleading information about the results of the election:
https://twitter.com/pchestek/status/1240027381894656005

Trying to get in the board of a charitable organization in an attempt to stear it away from its stated mission (the one supporters have trusted it to promote) is defenitely something that I considere hostile, yes.

**Comment by rafaelcastrocouto** [comment]
@Aspie96 
> Are you just going to state this as a claim

Yes I will because anyone with minimum intelligence in able to understand the reason after such a repeated and unfruitful debate

> Then, Coraline published misleading information

I'm sorry but _ad hominem_ the author just shows another imoral facet of your arguments

**Comment by Aspie96** [comment]
> Yes I will because anyone with minimum intelligence in able to understand the reason after such a repeated and unfruitful debate

"It's obvious that I'm right"

> I'm sorry but ad hominem the author just shows another imoral facet of your arguments

This is not an ad hominem fallacy. Showing an example of harmful behaviour to prove hostility is not what the ad hominem fallacy is.

The ad hominem fallacy is a "you're stupid/evil/whatever, therefore your argument is invalid" kind of argument. "This movement is hostile because those representing it did X and Y to promote it" is not an ad hominem fallacy.

(BTW, personal attacks are not fallacious, they are simply rude. It's only a logical fallacy if it's used to invalidate an argument).

**Comment by rafaelcastrocouto** [comment]
well at least you recognized you are being rude ... that's a start I guess 🤣

**Comment by realpixelcode** [comment]
>But I believe that by "real life" you refer to day to day informal interactions

Yes, right.

Well, Wikipedia also says: 

>The FSF considers free software to be a [subset](https://en.wikipedia.org/wiki/Subset) of open-source software, and Richard Stallman explained that [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) software, for example, can be developed as open source, despite that it does not give its users freedom (it restricts them), and thus doesn't qualify as free software.

That's quite similar to my opinion.

**Comment by Aspie96** [comment]
> well at least you recognized you are being rude ... that's a start I guess 🤣

That's a bit of a strawman, isn't it? I said personal attacks are not the same as ad hominem fallacies because I was explaining to you what an ad hominem fallacy is, and that is a common misconception (a personal attach *could* be a fallacy, but it doesn't have to be).

I'm rude to the extent to which a verifiable statement of fact, which I consider to be relevant, can be seen as a personal attack.

> > The FSF considers free software to be a [subset](https://en.wikipedia.org/wiki/Subset) of open-source software, and Richard Stallman explained that [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) software, for example, can be developed as open source, despite that it does not give its users freedom (it restricts them), and thus doesn't qualify as free software.
> That's quite similar to my opinion.

The FSF does indeed believe that free software is a subset of open source, but the disagreement is only about some very specific cases which are on the boundary of the category. The Hippocratic License would absolutely not be considered as "open source" by the FSF (although they would likely not care about the question).

You can see what they mean here:
https://www.gnu.org/philosophy/categories.html

> The term “open source” software is used by some people to mean more or less the same category as free software. It is not exactly the same class of software: they accept some licenses that we consider too restrictive, and there are free software licenses they have not accepted. However, the differences in extension of the category are small: we know of only a few cases of source code that is open source but not free.

And here:
https://www.gnu.org/philosophy/free-open-overlap.html

> Among all programs that are open source, only a minuscule fraction are not free. If the bottom row were drawn to scale, its text would have to be in a tiny font, perhaps too small to read.

They consider the terms to be almost synonymous (when it comes to software and licenses, obviously not when it comes the two movements, which they distinguish).

Please note that the FSF is fully aware of the many licenses for source-available software which are neither OSD-compliant nor "free software". They don't consider them to be "open source".

I'm not saying we should rely on what the FSF says, BTW, I am just giving context for that paragraph. It doesn't seem to mean what you seem to think it means. I believe the Wikipedia paragraph could have been clearer, but that is the opinion of the FSF.
